server:
  port: 8080

jomchen:
  domain:
    name: www.jomchen.top
  wechat:
    appsecret: dfa886fad88fe2cd72da2e642358b499
    appID: wx77747fc33d65088b
    token: 123456



# rabbitmq config
customer:
  rabbitmq:
    host: 192.168.0.105
    port: 5672
    username: guest
    password: guest
    virtualHost: /

spring:
  # redis config
  redis:
    host: 192.168.0.105
    password: 123456
    port: 6379
    database: 0

  # datasource
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: jomchen
    password: jomchen
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jomchen.test.model


