server:
  port: 8080

# rabbitmq config
customer:
  rabbitmq:
    host: 192.168.0.105
    port: 5672
    username: guest
    password: guest
    virtualHost: /

# redis config
spring:
  redis:
    host: 192.168.0.105
    password: 123456
    port: 6379
    database: 0

# datasource
datasource:
  mysql:
    url: jdbc:mysql://192.168.0.105:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: jomchen
    password: jomchen

