server:
  port: 8080

# rabbitmq config
customer:
  rabbitmq:
#    host: 10.0.0.16
    host: 192.168.0.105
    port: 5672
    username: guest
    password: guest
    virtualHost: /

# redis config
spring:
  redis:
    password: 123456
#    host: 10.0.0.16
    host: 192.168.0.105
    port: 6379
    database: 0

